### ISSUE TITLE
make an NPM package

### ISSUE THREAD

**Issue by frizman21** [watermarkchurch/contentful-shell#1]
- [x] bin/contentful should become an NPM package. 

Scope of this card also 
- [x] removes script from wmr.com and theporch.live
- [x] adds this new NPM package to those projects and everything builds / deploys correctly.

**Comment by jpowell** [comment]
Do we also need to update the version of the script?

**Comment by gburgett** [comment]
Part of this was getting it under the NPM versioning system in the first place.  So, the current version is the latest version and no need to update.
